#EJERCICIOS ARRAYS

### Ejercicio 1

Crea 3 nuevos arrays.
- Array de tipo entero, que contenga solo los números impares del 1 al 100.
- Array de tipo cadena con tu nombre y apellidos
- Array de tipo fechas, que contenga todos los días desde el 01Enero2020 al 04Febrero2020

In [ ]:
import numpy as np

array_impares = np.arange(0,100)
array_impares = array_impares [array_impares % 2 != 0]
print(array_impares)

print('\n')

array_cadena = np.array(['Antonio', 'Juan','González-Conde', 'Abril'], dtype=np.str_)
print(array_cadena)

print('\n')

array_fechas = np.array([], dtype=np.datetime64)
array_fechas= np.arange('2020-01-01', '2020-02-05', dtype='datetime64[D]')
print(array_fechas)


[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


['Antonio' 'Juan' 'González-Conde' 'Abril']


['2020-01-01' '2020-01-02' '2020-01-03' '2020-01-04' '2020-01-05'
 '2020-01-06' '2020-01-07' '2020-01-08' '2020-01-09' '2020-01-10'
 '2020-01-11' '2020-01-12' '2020-01-13' '2020-01-14' '2020-01-15'
 '2020-01-16' '2020-01-17' '2020-01-18' '2020-01-19' '2020-01-20'
 '2020-01-21' '2020-01-22' '2020-01-23' '2020-01-24' '2020-01-25'
 '2020-01-26' '2020-01-27' '2020-01-28' '2020-01-29' '2020-01-30'
 '2020-01-31' '2020-02-01' '2020-02-02' '2020-02-03' '2020-02-04']


### Ejercicio 2

Recupera los últimos 10 elementos del array de impares

In [ ]:
print(array_impares[-10:])
print(array_impares[:-11:-1])

[81 83 85 87 89 91 93 95 97 99]
[99 97 95 93 91 89 87 85 83 81]


### Ejercicio 3

Recorre el array de fechas, y genera un nuevo numpy array que contenga unicamente los días laborales

In [ ]:
array_laborales=array_fechas[np.is_busday(array_fechas)]


print(array_laborales)

['2020-01-01' '2020-01-02' '2020-01-03' '2020-01-06' '2020-01-07'
 '2020-01-08' '2020-01-09' '2020-01-10' '2020-01-13' '2020-01-14'
 '2020-01-15' '2020-01-16' '2020-01-17' '2020-01-20' '2020-01-21'
 '2020-01-22' '2020-01-23' '2020-01-24' '2020-01-27' '2020-01-28'
 '2020-01-29' '2020-01-30' '2020-01-31' '2020-02-03' '2020-02-04']


### Ejercicio 4

Genera la siguiente matriz.

$A = \begin{pmatrix}
10 & 1 & 8 & 4 \\
3 & 7 & 2 & 1 \\
0 & 2 & 20 & 12 \\
\end{pmatrix}$

¿De qué tipo es?
Luego, implementa una máscara a todos los números de la matriz mayores o iguales a 10

In [ ]:
a = np.array([[10, 1, 8, 4], [3, 7, 2, 1], [0, 2, 20, 12]])
np.asmatrix(a)
print(a,'\n')

masked = np.ma.masked_greater_equal(a, 10)
print(masked)

[[10  1  8  4]
 [ 3  7  2  1]
 [ 0  2 20 12]] 

[[-- 1 8 4]
 [3 7 2 1]
 [0 2 -- --]]


### Ejercicio 5

Crea dos fechas, la primera de ellas será tu fecha de nacimiento, y la segunda, la de un familiar o amigo tuyo.

¿Qué diferencia en horas hay entre las dos fechas?
¿Cual sería tu fecha de nacimiento si hubieras nacido 236 horas antes?

In [ ]:
date_1 = np.datetime64('2003-11-03')
date_2 = np.datetime64('2005-04-26')

days=date_2-date_1
print(days)

hours=days.astype('timedelta64[h]')
print(hours)

date_3=date_1-np.timedelta64(236, 'h')
print(date_3)

540 days
12960 hours
2003-10-24T04


### Ejercicio 6

Crea un array 1D con 50 elementos aleatorios entre -100 y 100. Aplica una máscara para que todos los valores negativos se conviertan en sus valores absolutos, pero solo si el valor es múltiplo de 3. Mantén los demás valores sin cambios.

In [ ]:
array_random=np.array([], dtype=np.int_)
array_random=np.random.randint(-100, 100, 50)
print(array_random)
print('\n')

array_random = np.ma.masked_where(array_random %3!=0, array_random)
array_random = np.ma.masked_where(array_random>=0, array_random)

array_random = (array_random*-1)
array_random.mask = False
print(array_random)
#abs(array_random.compressed())

[ 80 -41  -5 -66  70 -37  72 -79  73 -86 -47  61 -94  -7  35   8 -96  68
  31  71   6  -7  72  93 -48  57 -78 -52  50  91  15 -48  89 -52  55   7
 -55 -95   1  98  94 -11 -56  94  60 -97 -74  79  29 -90]


[80 -41 -5 66 70 -37 72 -79 73 -86 -47 61 -94 -7 35 8 96 68 31 71 6 -7 72
 93 48 57 78 -52 50 91 15 48 89 -52 55 7 -55 -95 1 98 94 -11 -56 94 60 -97
 -74 79 29 90]


#EJERCICIOS OPERACIONES

## Ejercicio 1

Genera un array que contenga 25 elementos entre 0 y 99 siguiendo una distribución lineal. Luego, transforma ese array en una matriz de 5 x 5. ¿Cuál es la diagonal de la matriz? ¿Y la diagonal justo superior?

In [6]:
import numpy as np

array_random=np.array([], dtype=np.int_)
array_random=np.random.randint(0, 100, 25)

array_random=np.asmatrix(array_random)
array_random=np.reshape(array_random, (5,5))

print(array_random)

print('\n',np.diag(array_random))
print('\n',np.diag(array_random, k=1))



[[20 36 20 36 24]
 [ 4 84 57 50 58]
 [ 1 61 80 40 96]
 [14 31 69 22 31]
 [87 56 92 98 65]]

 [20 84 80 22 65]

 [36 57 40 31]


## Ejercicio 2

Crea un de 5 x 4 con el valor repetido 10. Une esa matriz a la matriz del ejercicio anterior para conseguir dos nuevas matrices, una de  5 x 9, y otra de 9 x 5.

$m = \begin{pmatrix}
0 & 4 & 8 & 12 & 16 \\
20 & 24 & 28 & 32 & 36 \\
40 & 44 & 48 & 52 & 56 \\
60 & 64 & 68 & 72 & 76 \\
80 & 84 & 88 & 92 & 96
\end{pmatrix}$
$m2 = \begin{pmatrix}
5 & 5 & 5 & 5 & 5 \\
5 & 5 & 5 & 5 & 5 \\
5 & 5 & 5 & 5 & 5 \\
5 & 5 & 5 & 5 & 5 \\
5 & 5 & 5 & 5 & 5
\end{pmatrix}$

## Ejercicio 3

Teniendo el array inicial que podéis ver justo abajo, debéis realizar las operaciones necesarias para obtener el array:
    
array(['Este', 'Es', 'Un', 'Curso', 'De', 'IA'], dtype='<U12')

¿Qué elementos del array comienzan por 'E'?

In [8]:
array_texto = np.array(['Este', 'Es', 'Un', 'Curso', 'De', 'IA'], dtype='<U12')
for i in array_texto:
  if i.startswith('E'): print(i)

Este
Es


## Ejercicio 4

Considerando las matrices A y B.

$A = \begin{pmatrix}
3 & 1 & 2 \\
4 & 1 & 3 \\
2 & 0 & 1
\end{pmatrix}$
$B = \begin{pmatrix}
2 & 0 & 3 \\
1 & 1 & 1 \\
0 & 2 & 4
\end{pmatrix}$

- Realiza la multiplicación matricial de AxB y BxA. ¿Son iguales?
- Realiza la multiplicación de la matriz A x 2
- ¿Cúanto es la multiplicación escalar de AxB? ¿y de BxA?

In [12]:
matriz_a = np.array([[3, 1, 2], [4, 1, 3], [2, 0, 1]])
matriz_b = np.array([[2, 0, 3], [1, 1, 1], [0, 2, 4]])

print(matriz_a)
print('\n')
print(matriz_b)

#NO SON IGUALES

multplicacion_ab=np.dot(matriz_a,matriz_b)
print('\n')
print(multplicacion_ab)

multplicacion_ba=np.dot(matriz_b,matriz_a)
print('\n')
print(multplicacion_ba)

print('\n')
print(matriz_a*2)
#print(np.dot(matriz_a,2))

print('\n')
print(np.vdot(matriz_a,matriz_b))
print('\n')
print(np.vdot(matriz_b,matriz_a))


[[3 1 2]
 [4 1 3]
 [2 0 1]]


[[2 0 3]
 [1 1 1]
 [0 2 4]]


[[ 7  5 18]
 [ 9  7 25]
 [ 4  2 10]]


[[12  2  7]
 [ 9  2  6]
 [16  2 10]]


[[6 2 4]
 [8 2 6]
 [4 0 2]]


24


24


## Ejercicio 5

Usando la matriz A del ejercicio anterior, calcula:

- A^3
- El determinante de A
- Resuelve la ecuación Ax = y, siendo ***y*** el array [3,2,5]

# EJERCICIOS OPERACIONES 2

## Ejercicio 1

Usando el array que encontráis a continuación.

- ¿Hay algún valor múltiplo de 7?
- Devuelve un array con todos los nº menores de 40 o que sean múltiplos de 7

In [13]:
a = np.array([2, 5, 4, 2, 49, 34, 59, 21, 45, 6, 105])

## Ejercicio 2

Usando el array resultado del ejercicio anterior, calcula:
    
- El producto de todos sus valores
- Convierte el array el una matriz 3x3 y realiza la suma por filas
- Calcula el log10 de cada elemento de la matriz que acabas de crear

## Ejercicio 3

Haciendo uso de la matriz 3x3 creada en el ejercicio anterior y del siguiente array a, calcule:

$a = \begin{pmatrix}
0 & 3 & 5  \\
\end{pmatrix}$

- La suma de la matriz más el vector
- La división de ambos. ¿qué ocurre? Modifique el valor extraño por 0.
- El valor máximo de la matriz resultado de la división. ¿y por filas? ¿y por columnas?

## Ejercicio 4

In [14]:
array = np.array([44, 28,  8, 34, 34, 26, 32, 12, 28,  6, 19, 12, 46, 20, 20, 49, 18,
       19, 15, 15, 43,  3, 17, 33, 27, 10, 18,  2,  3,  3, 35, 35, 21, 17,
       36, 31, 16, 27,  6, 46, 29, 25, 26, 48, 30, 19, 18,  1, 43, 10, 32,
       15, 32, 30, 40, 41, 11, 46, 39,  5, 40,  1, 26, 10, 18, 26, 25, 25,
       21, 30, 12, 46,  1, 43,  1,  3, 26, 24,  0, 36, 34,  7, 26, 25, 41,
       22,  1, 16, 43,  1, 46, 14, 17, 39, 12,  9, 42, 48,  9, 45, 47, 32,
       15,  6, 40, 18,  6, 13, 35,  8, 46, 48, 26, 23, 12, 29, 21,  6,  3,
       22, 27, 16, 27, 10, 28, 23,  5, 24, 17, 43, 25, 11, 38, 40, 32, 42,
       27, 32,  6, 16, 18, 10, 18, 34, 34,  3,  4,  5,  4,  0, 35, 30,  9,
       16, 32, 46,  7, 10, 20, 13, 48,  8, 27, 27, 27, 16, 17, 12, 35, 31,
       21, 29, 15, 49, 14, 22, 18,  0, 13, 14, 39, 30,  4, 48,  1, 19, 33,
       39,  9,  0, 24,  6, 12, 24, 29, 16, 11, 12, 13, 11])

array

array([44, 28,  8, 34, 34, 26, 32, 12, 28,  6, 19, 12, 46, 20, 20, 49, 18,
       19, 15, 15, 43,  3, 17, 33, 27, 10, 18,  2,  3,  3, 35, 35, 21, 17,
       36, 31, 16, 27,  6, 46, 29, 25, 26, 48, 30, 19, 18,  1, 43, 10, 32,
       15, 32, 30, 40, 41, 11, 46, 39,  5, 40,  1, 26, 10, 18, 26, 25, 25,
       21, 30, 12, 46,  1, 43,  1,  3, 26, 24,  0, 36, 34,  7, 26, 25, 41,
       22,  1, 16, 43,  1, 46, 14, 17, 39, 12,  9, 42, 48,  9, 45, 47, 32,
       15,  6, 40, 18,  6, 13, 35,  8, 46, 48, 26, 23, 12, 29, 21,  6,  3,
       22, 27, 16, 27, 10, 28, 23,  5, 24, 17, 43, 25, 11, 38, 40, 32, 42,
       27, 32,  6, 16, 18, 10, 18, 34, 34,  3,  4,  5,  4,  0, 35, 30,  9,
       16, 32, 46,  7, 10, 20, 13, 48,  8, 27, 27, 27, 16, 17, 12, 35, 31,
       21, 29, 15, 49, 14, 22, 18,  0, 13, 14, 39, 30,  4, 48,  1, 19, 33,
       39,  9,  0, 24,  6, 12, 24, 29, 16, 11, 12, 13, 11])

Considerando el array de números que podéis encontrar justo arriba, calcula:

- Valor medio y mediano
- ¿Qué valor se encuentra en el tercer cuártil?
- ¿Qué valor se encuentra en el percentil 25? ¿y en el 50? ¿con qué valor coincide este último?
- ¿Cuál es la desviación estándar y la varianza del conjunto de datos?

La mediana es el valor central. Si el array tiene un número de elementos impar, la mediana se calcula como la media de los dos valores centrales